[package]
name = "click_ward"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
camino = "1.1.7"
clap = { version = "4.5", features = ["cargo", "derive", "env", "wrap_help"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
